--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/ItsGabry/NanoBinGUI
branches:
- master
projects:
  NanoBinGUI:
    path: ""
    libs: 
    - src: muqsit/InvMenu/InvMenu
      version: ^2.1.0
...
